// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoIProgra2.Data;

#nullable disable

namespace ProyectoIProgra2.Migrations
{
    [DbContext(typeof(MyAppDbContext))]
    [Migration("20260618060518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoIProgra2.Entidades.BloqueoMesa", b =>
                {
                    b.Property<int>("BloqueoMesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BloqueoMesaId"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MesaId")
                        .HasColumnType("integer");

                    b.HasKey("BloqueoMesaId");

                    b.ToTable("BloqueosMesas");

                    b.HasData(
                        new
                        {
                            BloqueoMesaId = 1,
                            Detalle = "Mantenimiento de mesa",
                            Fecha = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 15, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 2
                        },
                        new
                        {
                            BloqueoMesaId = 2,
                            Detalle = "Evento privado",
                            Fecha = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 6
                        },
                        new
                        {
                            BloqueoMesaId = 3,
                            Detalle = "Limpieza profunda",
                            Fecha = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 10
                        },
                        new
                        {
                            BloqueoMesaId = 4,
                            Detalle = "Reserva especial",
                            Fecha = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 18, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 3
                        },
                        new
                        {
                            BloqueoMesaId = 5,
                            Detalle = "Inspección de zona VIP",
                            Fecha = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 19, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 19, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 9
                        });
                });

            modelBuilder.Entity("ProyectoIProgra2.Entidades.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ced")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tel")
                        .HasColumnType("integer");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Apellidos = "Pérez López",
                            Ced = 101110111,
                            Email = "juan@email.com",
                            Nombre = "Juan",
                            Tel = 88881111
                        },
                        new
                        {
                            ClienteId = 2,
                            Apellidos = "González Mora",
                            Ced = 202220222,
                            Email = "maria@email.com",
                            Nombre = "María",
                            Tel = 88882222
                        },
                        new
                        {
                            ClienteId = 3,
                            Apellidos = "Rodríguez Soto",
                            Ced = 303330333,
                            Email = "carlos@email.com",
                            Nombre = "Carlos",
                            Tel = 88883333
                        },
                        new
                        {
                            ClienteId = 4,
                            Apellidos = "Martínez Cruz",
                            Ced = 404440444,
                            Email = "ana@email.com",
                            Nombre = "Ana",
                            Tel = 88884444
                        },
                        new
                        {
                            ClienteId = 5,
                            Apellidos = "Hernández Vega",
                            Ced = 505550555,
                            Email = "luis@email.com",
                            Nombre = "Luis",
                            Tel = 88885555
                        },
                        new
                        {
                            ClienteId = 6,
                            Apellidos = "Ramírez Quirós",
                            Ced = 606660666,
                            Email = "sofia@email.com",
                            Nombre = "Sofía",
                            Tel = 88886666
                        },
                        new
                        {
                            ClienteId = 7,
                            Apellidos = "Vargas Jiménez",
                            Ced = 707770777,
                            Email = "diego@email.com",
                            Nombre = "Diego",
                            Tel = 88887777
                        },
                        new
                        {
                            ClienteId = 8,
                            Apellidos = "Castro Solano",
                            Ced = 808880888,
                            Email = "valeria@email.com",
                            Nombre = "Valeria",
                            Tel = 88888888
                        },
                        new
                        {
                            ClienteId = 9,
                            Apellidos = "Mora Brenes",
                            Ced = 909990999,
                            Email = "andres@email.com",
                            Nombre = "Andrés",
                            Tel = 88889999
                        },
                        new
                        {
                            ClienteId = 10,
                            Apellidos = "Rojas Campos",
                            Ced = 101010101,
                            Email = "camila@email.com",
                            Nombre = "Camila",
                            Tel = 88880000
                        },
                        new
                        {
                            ClienteId = 11,
                            Apellidos = "Núñez Alfaro",
                            Ced = 111111110,
                            Email = "sebastian@email.com",
                            Nombre = "Sebastián",
                            Tel = 87771111
                        },
                        new
                        {
                            ClienteId = 12,
                            Apellidos = "Flores Madrigal",
                            Ced = 121212120,
                            Email = "isabella@email.com",
                            Nombre = "Isabella",
                            Tel = 87772222
                        },
                        new
                        {
                            ClienteId = 13,
                            Apellidos = "Chaves Araya",
                            Ced = 131313130,
                            Email = "mateo@email.com",
                            Nombre = "Mateo",
                            Tel = 87773333
                        },
                        new
                        {
                            ClienteId = 14,
                            Apellidos = "Segura Monge",
                            Ced = 141414140,
                            Email = "daniela@email.com",
                            Nombre = "Daniela",
                            Tel = 87774444
                        },
                        new
                        {
                            ClienteId = 15,
                            Apellidos = "Herrera Vindas",
                            Ced = 151515150,
                            Email = "gabriel@email.com",
                            Nombre = "Gabriel",
                            Tel = 87775555
                        });
                });

            modelBuilder.Entity("ProyectoIProgra2.Entidades.EstadoDeReserva", b =>
                {
                    b.Property<int>("EstadoDeReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstadoDeReservaId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EstadoDeReservaId");

                    b.ToTable("EstadoDeReservas");

                    b.HasData(
                        new
                        {
                            EstadoDeReservaId = 1,
                            Estado = "Activa"
                        },
                        new
                        {
                            EstadoDeReservaId = 2,
                            Estado = "Cancelada"
                        },
                        new
                        {
                            EstadoDeReservaId = 3,
                            Estado = "Atendida"
                        });
                });

            modelBuilder.Entity("ProyectoIProgra2.Entidades.ListaDeEspera", b =>
                {
                    b.Property<int>("ListaDeEsperaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ListaDeEsperaId"));

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HoraSolicitud")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.HasKey("ListaDeEsperaId");

                    b.ToTable("ListasDeEspera");

                    b.HasData(
                        new
                        {
                            ListaDeEsperaId = 1,
                            CantidadPersonas = 4,
                            ClienteId = 3,
                            HoraSolicitud = new DateTime(2026, 6, 15, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            TurnoId = 2
                        },
                        new
                        {
                            ListaDeEsperaId = 2,
                            CantidadPersonas = 2,
                            ClienteId = 4,
                            HoraSolicitud = new DateTime(2026, 6, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TurnoId = 3
                        },
                        new
                        {
                            ListaDeEsperaId = 3,
                            CantidadPersonas = 3,
                            ClienteId = 6,
                            HoraSolicitud = new DateTime(2026, 6, 16, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            TurnoId = 1
                        },
                        new
                        {
                            ListaDeEsperaId = 4,
                            CantidadPersonas = 5,
                            ClienteId = 9,
                            HoraSolicitud = new DateTime(2026, 6, 17, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            TurnoId = 2
                        },
                        new
                        {
                            ListaDeEsperaId = 5,
                            CantidadPersonas = 2,
                            ClienteId = 12,
                            HoraSolicitud = new DateTime(2026, 6, 18, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            TurnoId = 3
                        });
                });

            modelBuilder.Entity("ProyectoIProgra2.Entidades.Mesa", b =>
                {
                    b.Property<int>("MesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MesaId"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<int>("ZonaId")
                        .HasColumnType("integer");

                    b.HasKey("MesaId");

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            MesaId = 1,
                            Capacidad = 4,
                            ZonaId = 1
                        },
                        new
                        {
                            MesaId = 2,
                            Capacidad = 2,
                            ZonaId = 1
                        },
                        new
                        {
                            MesaId = 3,
                            Capacidad = 6,
                            ZonaId = 1
                        },
                        new
                        {
                            MesaId = 4,
                            Capacidad = 4,
                            ZonaId = 2
                        },
                        new
                        {
                            MesaId = 5,
                            Capacidad = 2,
                            ZonaId = 2
                        },
                        new
                        {
                            MesaId = 6,
                            Capacidad = 8,
                            ZonaId = 2
                        },
                        new
                        {
                            MesaId = 7,
                            Capacidad = 4,
                            ZonaId = 3
                        },
                        new
                        {
                            MesaId = 8,
                            Capacidad = 6,
                            ZonaId = 3
                        },
                        new
                        {
                            MesaId = 9,
                            Capacidad = 4,
                            ZonaId = 4
                        },
                        new
                        {
                            MesaId = 10,
                            Capacidad = 8,
                            ZonaId = 4
                        });
                });

            modelBuilder.Entity("ProyectoIProgra2.Entidades.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservaId"));

                    b.Property<int>("CantidaPersonas")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoDeReservaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MesaId")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.HasKey("ReservaId");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            ReservaId = 1,
                            CantidaPersonas = 3,
                            ClienteId = 1,
                            EstadoDeReservaId = 1,
                            Fecha = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 1,
                            TurnoId = 2
                        },
                        new
                        {
                            ReservaId = 2,
                            CantidaPersonas = 2,
                            ClienteId = 2,
                            EstadoDeReservaId = 1,
                            Fecha = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 15, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 4,
                            TurnoId = 3
                        },
                        new
                        {
                            ReservaId = 3,
                            CantidaPersonas = 4,
                            ClienteId = 3,
                            EstadoDeReservaId = 1,
                            Fecha = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 16, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 16, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 7,
                            TurnoId = 1
                        },
                        new
                        {
                            ReservaId = 4,
                            CantidaPersonas = 5,
                            ClienteId = 4,
                            EstadoDeReservaId = 1,
                            Fecha = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 3,
                            TurnoId = 2
                        },
                        new
                        {
                            ReservaId = 5,
                            CantidaPersonas = 2,
                            ClienteId = 5,
                            EstadoDeReservaId = 1,
                            Fecha = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 5,
                            TurnoId = 3
                        },
                        new
                        {
                            ReservaId = 6,
                            CantidaPersonas = 6,
                            ClienteId = 6,
                            EstadoDeReservaId = 1,
                            Fecha = new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 17, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 17, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 8,
                            TurnoId = 1
                        },
                        new
                        {
                            ReservaId = 7,
                            CantidaPersonas = 4,
                            ClienteId = 7,
                            EstadoDeReservaId = 1,
                            Fecha = new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 17, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 9,
                            TurnoId = 2
                        },
                        new
                        {
                            ReservaId = 8,
                            CantidaPersonas = 7,
                            ClienteId = 8,
                            EstadoDeReservaId = 1,
                            Fecha = new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 17, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 17, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 6,
                            TurnoId = 1
                        },
                        new
                        {
                            ReservaId = 9,
                            CantidaPersonas = 4,
                            ClienteId = 9,
                            EstadoDeReservaId = 1,
                            Fecha = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 18, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 10,
                            TurnoId = 2
                        },
                        new
                        {
                            ReservaId = 10,
                            CantidaPersonas = 2,
                            ClienteId = 10,
                            EstadoDeReservaId = 2,
                            Fecha = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 18, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 18, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 2,
                            TurnoId = 3
                        },
                        new
                        {
                            ReservaId = 11,
                            CantidaPersonas = 3,
                            ClienteId = 11,
                            EstadoDeReservaId = 1,
                            Fecha = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 18, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 18, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 1,
                            TurnoId = 1
                        },
                        new
                        {
                            ReservaId = 12,
                            CantidaPersonas = 4,
                            ClienteId = 12,
                            EstadoDeReservaId = 1,
                            Fecha = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 19, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 4,
                            TurnoId = 2
                        },
                        new
                        {
                            ReservaId = 13,
                            CantidaPersonas = 3,
                            ClienteId = 13,
                            EstadoDeReservaId = 3,
                            Fecha = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 19, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 19, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 7,
                            TurnoId = 3
                        },
                        new
                        {
                            ReservaId = 14,
                            CantidaPersonas = 6,
                            ClienteId = 14,
                            EstadoDeReservaId = 1,
                            Fecha = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 3,
                            TurnoId = 1
                        },
                        new
                        {
                            ReservaId = 15,
                            CantidaPersonas = 2,
                            ClienteId = 15,
                            EstadoDeReservaId = 1,
                            Fecha = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 20, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 5,
                            TurnoId = 2
                        },
                        new
                        {
                            ReservaId = 16,
                            CantidaPersonas = 4,
                            ClienteId = 15,
                            EstadoDeReservaId = 1,
                            Fecha = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraFin = new DateTime(2026, 6, 20, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new DateTime(2026, 6, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            MesaId = 9,
                            TurnoId = 3
                        });
                });

            modelBuilder.Entity("ProyectoIProgra2.Entidades.Turno", b =>
                {
                    b.Property<int>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TurnoId"));

                    b.Property<int>("HoraFin")
                        .HasColumnType("integer");

                    b.Property<int>("HoraInicio")
                        .HasColumnType("integer");

                    b.HasKey("TurnoId");

                    b.ToTable("Turnos");

                    b.HasData(
                        new
                        {
                            TurnoId = 1,
                            HoraFin = 11,
                            HoraInicio = 8
                        },
                        new
                        {
                            TurnoId = 2,
                            HoraFin = 17,
                            HoraInicio = 12
                        },
                        new
                        {
                            TurnoId = 3,
                            HoraFin = 22,
                            HoraInicio = 18
                        });
                });

            modelBuilder.Entity("ProyectoIProgra2.Entidades.Zona", b =>
                {
                    b.Property<int>("ZonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ZonaId"));

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ZonaId");

                    b.ToTable("Zonas");

                    b.HasData(
                        new
                        {
                            ZonaId = 1,
                            Seccion = "Interior"
                        },
                        new
                        {
                            ZonaId = 2,
                            Seccion = "Terraza"
                        },
                        new
                        {
                            ZonaId = 3,
                            Seccion = "Jardín"
                        },
                        new
                        {
                            ZonaId = 4,
                            Seccion = "VIP"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
